### ISSUE TITLE
Cooperative Async Copies

### ISSUE THREAD

**Issue by FabianSchuetze** [Bruce-Lee-LY/cuda_hgemm#5]
Thanks for this wonderful repo.

I have a question about the [async copies](https://github.com/Bruce-Lee-LY/cuda_hgemm/blob/master/src/wmma/wmma_async.cu#L105C1-L108C74):
```
uint32_t A_smem_lane_addr =
   __cvta_generic_to_shared(&smem[A_smem_idx][0]) + (lane_id % CHUNK_COPY_LINE_LANES) * THREAD_COPY_BYTES;

CP_ASYNC_CG(A_smem_lane_addr, A_lane_ptr, THREAD_COPY_BYTES);
```
Does this mean that every lane (thread) has a different pointer to the shared memory and a different pointer to the global memory?

The way I understand the async copies, the src and dst pointers must be the same for every thread in the thread block. See the [docs](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#asynchronous-data-copies).

**Comment by Bruce-Lee-LY** [comment]
You should refer to the [docs](https://docs.nvidia.com/cuda/archive/11.3.0/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-asynchronous-copy).

**Comment by FabianSchuetze** [comment]
Thanks.
