### ISSUE TITLE
Question about the tiling size

### ISSUE THREAD

**Issue by macto94** [Bruce-Lee-LY/cuda_hgemm#6]
First of all, I would like to express my deep gratitude for providing the excellent educational materials. The articles posted on Medium have also been very helpful in my studies.

I have a question. I am using an A100 GPU. I have noticed that the performance shown on the A6000 you demonstrate seems to reach throughput almost close to cublas for certain kernels.
When I tested it on my A100, it showed the following performance (I fixed M=512 instead of M=N=K).
After considering, I think I need to change the tiling size because I did not keep the dimensions the same. Do you think I am heading in the right direction?

If so, could you explain how you decided on the current tiling size and other "execution config" settings? (Or did you just search for all these settings?)

Thank you once again.

![스크린샷 2024-01-03 오후 2 40 10](https://github.com/Bruce-Lee-LY/cuda_hgemm/assets/55390981/8a99a3e7-5725-4f38-bdfd-b3f1c8a68471)

**Comment by Bruce-Lee-LY** [comment]
Indeed, you need to modify the tiling size to approximate the ratio of M to K. If M is much smaller than K, you also need to consider the splitk method.

**Comment by macto94** [comment]
And, I don't understand why you set the `BLOCK_ROW_WARPS` as `BLOCK_COLS / WARP_COLS`, not `BLOCK_ROW_WARPS / WARP_ROWS`.
I'm sorry to bother you with these simple questions as I am a newbie to CUDA.
Thank you.
```
#define BLOCK_ROWS 256
#define BLOCK_COLS 128
...
#define BLOCK_ROW_WARPS 2 // BLOCK_COLS / WARP_COLS
#define BLOCK_COL_WARPS 4 // BLOCK_ROWS / WARP_ROWS
```
