### ISSUE TITLE
关于permute实现方式

### ISSUE THREAD

**Issue by feiyuvl** [Bruce-Lee-LY/cuda_hgemm#8]
您好，在看mma_permuted.cu源码时，发现您使用的permute方式和`DEVELOPING CUDA KERNELS TO  PUSH TENSOR CORES TO THE  ABSOLUTE LIMIT ON NVIDIA A100`文档中所提到的xor方式好像有所区别。您使用的是在不同stage使用循环右移的方式来避免ldmatrix时的bank conflict，不知道理解的正不正确，希望能抽空帮忙解答，感谢。

**Comment by Bruce-Lee-LY** [comment]
对的

**Comment by SuperCB** [comment]
> 您好，在看mma_permuted.cu源码时，发现您使用的permute方式和`DEVELOPING CUDA KERNELS TO PUSH TENSOR CORES TO THE ABSOLUTE LIMIT ON NVIDIA A100`文档中所提到的xor方式好像有所区别。您使用的是在不同stage使用循环右移的方式来避免ldmatrix时的bank conflict，不知道理解的正不正确，希望能抽空帮忙解答，感谢。

我也在看这部分但是没太懂，可否解答一下？

**Comment by youzjuer** [comment]
> > 您好，在看mma_permuted.cu源码时，发现您使用的permute方式和`DEVELOPING CUDA KERNELS TO PUSH TENSOR CORES TO THE ABSOLUTE LIMIT ON NVIDIA A100`文档中所提到的xor方式好像有所区别。您使用的是在不同stage使用循环右移的方式来避免ldmatrix时的bank conflict，不知道理解的正不正确，希望能抽空帮忙解答，感谢。
> 
> 我也在看这部分但是没太懂，可否解答一下？

![image](https://github.com/user-attachments/assets/08b7ea9e-21f4-4fa2-915d-320ef068deba)
就是类似于swizzle的东西
